#maven_install(
#    artifacts = [
#        "androidx.appcompat:appcompat:1.1.0",
#        "androidx.annotation:annotation:1.1.0",
#        "com.google.android.material:material:1.0.0",
#        "androidx.constraintlayout:constraintlayout:1.1.3",
#        "androidx.navigation:navigation-fragment-ktx:2.1.0",
#        "androidx.navigation:navigation-ui-ktx:2.1.0"
#
#    ],
#    repositories = [
#        "https://jcenter.bintray.com/",
#        "https://maven.google.com",
#        "https://repo1.maven.org/maven2",
#    ],
#)
